apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rani19/backend:latest # Ensure this is your latest image with the /healthz and /metrics exclusion logic
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:12345678@postgres:5432/shop_inventory"
          # --- IMPORTANT: Liveness and Readiness Probes Added ---
          livenessProbe:
            httpGet:
              path: /healthz # Probe hits the dedicated health endpoint
              port: 5000
            initialDelaySeconds: 10 # Wait 10 seconds before starting checks
            periodSeconds: 5      # Check every 5 seconds
            timeoutSeconds: 3     # Timeout after 3 seconds
            failureThreshold: 3   # Mark as unhealthy after 3 consecutive failures
          readinessProbe:
            httpGet:
              path: /healthz # Probe hits the dedicated health endpoint
              port: 5000
            initialDelaySeconds: 5  # Wait 5 seconds before starting checks
            periodSeconds: 5        # Check every 5 seconds
            timeoutSeconds: 3       # Timeout after 3 seconds
            failureThreshold: 3     # Don't send traffic after 3 consecutive failures
