    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: frontend
      namespace: default # <-- CRUCIAL: Explicitly set the namespace for the deployment
    spec:
      replicas: 1 # Or your desired replica count
      selector:
        matchLabels:
          app: frontend
      template:
        metadata:
          labels:
            app: frontend
        spec:
          containers:
            - name: frontend
              image: rani19/gogo-main-frontend:latest
              ports:
                - containerPort: 80
              env:
                - name: VITE_API_URL
                  value: "http://backend:5000/api" # <-- Corrected URL for backend in default namespace
    