    apiVersion: v1
    kind: Service
    metadata:
      name: frontend
      namespace: default # <-- CRUCIAL: Explicitly set the namespace for the service
    spec:
      selector:
        app: frontend
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
      type: ClusterIP
    