apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-recording-rules
              mountPath: /etc/prometheus/rules/recording
              readOnly: true
            - name: prometheus-alerting-rules
              mountPath: /etc/prometheus/rules/alerting
              readOnly: true
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-recording-rules
          configMap:
            name: prometheus-recording-rules
        - name: prometheus-alerting-rules
          configMap:
            name: prometheus-alerting-rules
