version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gogo-jenkins
    user: root
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kubeconfig:/var/jenkins_home/.kube/config
    networks:
      - gogo-net
    dns:
      - 8.8.8.8  # ✅ לפתור בעיות DNS בחיבור לאינטרנט

networks:
  gogo-net:
    driver: bridge
