apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: prometheus
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'Rani.saed19@gmail.com'
      smtp_auth_username: 'Rani.saed19@gmail.com'
      smtp_auth_password: 'gqym ykzj weig kfxn'
      smtp_require_tls: true

    route:
      receiver: 'email-alert'
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
      - name: 'email-alert'
        email_configs:
          - to: 'Rani.saed19@gmail.com'
            send_resolved: true
